#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(APPLICATION_EVENT);

enum {
    APPLICATION_EVENT_CARD_SCANNED,
    APPLICATION_EVENT_BUTTON_PRESS,
    APPLICATION_EVENT_SET_UNLOCKED,
    APPLICATION_EVENT_BLINK_ERROR,
    APPLICATION_EVENT_FIRMWARE_UPDATE,
    APPLICATION_EVENT_REBOOT,
};

#define CARD_ID_MAX_LEN 8